flowforge/handbook

company/communication.md
company/index.md

Most mistakes I've made in the past around communications and scheduling
are miscommunications around times and their notation, or timezones
with offsets.
For timezones, most servers are set to UTC for convenience. While this
is not the reason to recommend it, it was the inspiration to suggest it
for the company too. When one goes into summer time, their offset
changes, and only theirs. Putting the responsibility on each and
everyone to remember the offset tot UTC is more convenient for the
entire company.
Around times themself: a 24 hour clock unambiguously communicates when a
meeting is to take place. Using AM/PM is fine though, but has to be
explicitly communicated.

communication: Add guidance on times and timezones

---

README.md
company/index.md

Due to the way the handbook content is published on the website, links between pages have to be handled slightly strangely to ensure the generated links work as expected.

Fix links to communications page

---

company/communication.md

This change is mostly a carbon copy of how most meetings were run at
GitLab. What I think is great about most of these points:
- It allows everyone to have a voice
- Highly focussed meetings on what's the agenda
- Great documentation for non-participants after the meeting
All things considered it might be bit of work to get used to, but worth
the initial pain.

communication: Document how to run meetings

---

development/index.md

To encourage a celebrative moment and social calls organize a lunch
each 4 weeks to meet and eat.

development: Introduce Launch Lunch

---

development/index.md

This was discussed in a meeting today, capturing it in the handbook now
to formalize it.

development: Document when to retro/kick-off a release

---

README.md
peopleops/index.md

Unlimited PTO can lead to a race to the bottom, hope this policy
prevents such a race. Further there's legal requirements to document
when someone has taken vacation to prove they've taken it. This too is
now documented.
Closes #10

peopleops: Document vacation policy

---

development/packaging.md

Until GitHub add the missing feature of automatically adding issues/prs to project boards, we have to add a GH Action to each repository to do it for us.
This PR adds guidance on how to do that as part of our repository setup requirements.

Add requirement to setup project-automation on new repositories

---

company/values.md

This commit does a few things:
1. Fix the formatting of the markdown to stay within 80 char limits.
This is a personal preference, so this change limits it to this page
just so I was able to parse what we had already.
2. Create a header: "Be Effective", all our values combined already
wanted this from us at this company, just implimitly. However, being
explicit we could subdivide the values in two classes: Results and
Communication (having a shared set of goals).
3. Add "Be Trusting" to the list of values. The why is described in the
changeset itself.

values: Update the list with "Be Trusting"

---

peopleops/index.md

Currently there's no way to record sick leave, so this change just makes
this the policy. There seems to be no requirement in the UK or NL to
record this if it's short term. As such, this policy should *hopefully*
last us very long.

peopleops: Don't record sick leave

---

peopleops/index.md

For auditing reasons, each Brex transaction requires a receipt to be
attached.

expenses: Require receipts to tbe uploaded

---

company/communication.md

To make scroll back managable, and allow for quick scanning of channels
with higher traffic, we should use threads much more. Now it's hard to
understand when discussions start and end. Also, concurrent discussions
are very hard to follow.

communication: Use Slack threads

---

peopleops/index.md

Chain of changes has 2 commits:
```
benefits: Add constraints to costs for conferences
Wording of the previous iteration was broad and unbounded, and while
FlowForge might someday fund (part of) a masters degree, at this time
it's financially not wise to have broad wording around educational
benefits.
```
and
```
fix: Address by title for responsibilities over names
While not a big problem or issue, when there's responsibilities related
to a certain role the handbook should address the role. This prevents
rewrites when the organisation changes in terms of personal, or who
authorizes what.
```

Benefits reword

---

company/communication.md

At this company we've got two weekly meetings, this change documents the
structure as is with a proposed new structure for the Tuesday meeting.
The new additions are two fold:
1. Reviewing on the weekend from a personal standpoint
Hoping this will aid in team bonding
2. Open Mic
When ideas are unfinished in ones head, issues aren't created yet.
Having a place to discuss such ideas allows everyone to chip in
improvements to move these ideas along and into issues.

weekly meeting: Propose new structure

---

company/team.md

Culture is taught to new hires, and created by a whole team. It's not
static, and thus it's hard to hire for. Values are much more stable and
thus easier to hire for. Trust that if the values are shared, the
culture will follow, and thus hire for value fit.

company: Hire for value fit over culture fit

---

company/communication.md

As status meetings are moved to Slack, 2 meetings are folded into one.
Main idea behind the meeting is to get to know each other, and company
wide announcements.

meetings: Standardize on one Wednesday meeting

---

development/staging.md

I was confused using staging due to the listed domain. The domain has
not been published to prevent production users of trying the wrong
domain.

development: Reword domain location to use staging

---

development/index.md

Adds details of the two new project boards.
This will replace #43

Updating planning workflow

---

development/release.md

Added details about waiting between npm publishes
Also make sure git user.name and user.email are set before running `prepare-release` script

Update release instructions

---

company/product-vision.md

Introducing configuration almost always comes from a developer wanting
to provide options, where product needs to be more assertive with making
a choice. So with this change, this is a decision that defaults to no
config, and sane defaults.

product: Document Convention over Configuration

---

development/index.md

The list was getting outdated, even 0.8 was missing among 0.9.

releases: Update the releases list

---

peopleops/compensation.md

For taxes the 409A valuation might be very important for FlowForge
employees. As such an internal document was created for them to look at,
and now linked in the handbook so they can actually find it.

peopleops: Link to internal 409A valuation doc

---

development/packaging.md

Ticking off my todo item from the 0.8 retrospective
This adds details of where extra nodes should be added to the default stacks.

Add instructions for bundling nodes into stacks

---

peopleops/compensation.md

Recently I've been asked what data source we use to check if we're competitive. As there's no reason not to be open about our data source I've included it in the handbook now.

peopleops: Disclose our data source for comp data

---

development/release.md
peopleops/compensation.md

In practise the lunch was organised already, but was never reintroduced in the handbook. This change commits it again.

peopleops: Reintroduce the Launch Lunch

---

product/plan.md

Following offline discussions on the 'convention over configuration' principle, this is an attempted rewording that I think hits the right balance between the two.
The emphasis is very much that we start from a position of *not* exposing options to the user if it can be avoided - whilst acknowledging there will be justifiable cases for giving users a choice.
This replaces #106

Reword convention over config principle

---

README.md

Re-organising the main table of contents to make it easier to navigate around the different sections of the Handbook. Also renamed "Colophon" as I felt that was unclear.
**Before:**
**After:**

Clean the primary Table of Contents

---

operations/support.md

To make support scalable long term, the intent should always be to reply with links to docs, articles, or other content.

support: Reply with links to docs

---

peopleops/index.md

Proposal to add mileage explicitly to allowable expenses, based on HMRC and Tax and Customs Administration Netherlands guidance.

Add mileage as a possible expense

---

development/packaging.md

This documents the standard set of labels we apply to our repositories.
This PR introduces some changes to our existing labels.
- Adds priority labels (p-1, p-2, p-3)
- Renames the product scope labels to have the `scope:` prefix
- Adds some other functional areas that should be highlighted
To create this list, I've looked at what labels we have across all repositories (if you're interested... https://docs.google.com/spreadsheets/d/1iVZxoBRkDt8tZ0izKvgaq8JefKB6qQTGnT2gLDZFigE/edit?usp=sharing)
Some repos have the GitHub-defined set of default labels - many of which we don't use. We have some duplication (`docs` and `documentation` for eg). 
Once this PR is approved in principle, the follow-on actions are:

Add list of standard labels for repositories

---

development/packaging.md

Assuming https://github.com/flowforge/admin/pull/113 is merged, this adds reference to the New Repo Checklist to our packaging requirements docs.

Add reference to New Repo Checklist issue

---

peopleops/hiring.md
peopleops/index.md

While we've got Pilot and BambooHR, there's no consistent overview with open roles, the current team, and what roles are filled. To fix that I've started a spreadsheet. This sheet can only stay consistent if we update it. So I've added it to the handbook to be updated.

peopleops: process to create a consistent overview

---

media/index.md

When I imported the clips for the release 1.1 video they didn't seem to fit, after some tinkering I'm pretty sure 1800 is the correct width to match the mask.

Change the video resolution to be correct

---

peopleops/index.md

While transparency is a value, it's not great to share compensation and performance details.

peopleops: Make team details private

---

peopleops/hiring.md

Our job offer template was a copy-paste off an offer extended right before it. This created errors or missing details. By using a standardized template these errors will be prevented.

peopleops: Link to offer template for candidates

---

development/index.md

As 2023 is approaching a reference to 20 January is nearly ambiguous. This change adds a year to a date to fix this.

Explicit year referring to a date

---

design/index.md

We'd said that 'how tos' should be sent to the mailing list but not the blog, that's the wrong way around.

fix channels for howtos

---

development/release.md

Adds a check that the release manager has password-less access to github from the git cli

Add check for git cli access in release prereqs

---

README.md
company/index.md
design/index.md
development/index.md
marketing/index.md
media/index.md
operations/index.md
peopleops/index.md
product/index.md

With the newly introduced side-navigation for our handbook, we have the option to make "pretty" navigation titles. Have added these into some of the `md` files to make the side navigation easier to parse and read.
The `navGroup` parameter that has been added is in preparation of a second stage, where the top-level navigation will mimic the grouping currently seen in `/handbook/index.md`. Functionality to produce those groups has been added in the attached Website PR, but is not currently used when rendering into the HTML templates (a future piece of work will do this)
Issue: https://github.com/flowforge/website/issues/193
Paired with development changes in [Website PR](https://github.com/flowforge/website/pull/304)

Add Handbook meta data for Website Rendering

---

company/index.md
company/principles.md
company/values.md

Split out the sections of the Company Handbook section so that relevant categories appear in the side navigation for easier finding.
https://github.com/flowforge/handbook/issues/180 - Part of the Handbook cleaning

Split Company to make it easier to navigate

---

design/branding.md
design/design-thinking.md
design/index.md
design/process.md
design/tools.md

Split out the sections of the Design Handbook section so that relevant categories appear in the side navigation for easier finding.
https://user-images.githubusercontent.com/99246719/211110602-55761b72-e474-4b3d-9dbe-54e3651a3943.mov
https://github.com/flowforge/handbook/issues/180 - Part of the Handbook cleaning

Split out Design section to make it easier to navigate

---

product/customer-calls.md
product/demos.md
product/index.md
product/pricing.md
product/verticals.md

Split out the sections of the Product Handbook section so that relevant categories appear in the side navigation for easier finding.
https://github.com/flowforge/handbook/issues/180 - Part of the Handbook cleaning

Split Product to make it easier to navigate

---

.github/scripts/package.json
.github/scripts/tests/valid-links.js
.github/workflows/test.yml
.gitignore

Add npm testing content into .github folder to retain handbook hierarchy.
[](https://github.com/flowforge/website/issues/315)
- [-] Configuration details
- [-] Concepts
- [-] Backport needed? -> add the `backport` label
- [-] Includes a DB migration? -> add the `area:migration` label

Add npm test files for checking valid links

---

README.md

If I click a link to values, its surprising to be redirected to a page that's not the values page. This change fixes that.

navigation: Fix link to values

---

company/board.md
company/communication.md
company/principles.md
company/security.md
company/strategy.md
company/values.md
design/design-thinking.md
development/frontend/data-attributes.md
development/frontend/index.md
development/frontend/services.md
development/frontend/testing.md
development/how-we-work/packaging.md
development/releases/index.md
development/releases/planning.md
marketing/blog.md
marketing/channels.md
marketing/types.md
marketing/website.md
operations/accounts.md
operations/billing.md
operations/change.md
operations/data.md
operations/support.md
operations/vendors.md
peopleops/compensation.md
peopleops/expenses.md
peopleops/hiring.md
product/plan.md
product/versioning.md

Adds `navTitle` or `meta.title` where relevant. The latter is used where we _only_ want it to show in the title of the tab/share, not in the side navigation of the Handbook.
It's on my todo list to write a section in the handbook about the different properties/fields we have available.
Linked to https://github.com/flowforge/website/pull/374 as that enabled the inclusion of these in the page titles.

Improve page titles for sharing

---

development/frontend/services.md

Noticed (when using it) that the example for the Dialog service in our front-end development guides has an incorrect import statement

Fix typo in Dialog import statement

---

development/releases/planning.md

This is a redo of #174 which had merge conflicts following handbook reorganisation.
In hindsight, the merge conflicts weren't as hard to resolve as I thought, but this is a clean branch with the changes reapplied. The contents hasn't changed.
Given the approval against 174, I'll self merge this.

Add docs on feature demos

---

company/communication.md

The weekly call is now around KPIs and personal updates, this conflates the meeting and makes it unfocussed. Now the team is growing we'd create a meeting where department leaders will inform and discuss their progress.

meeting: Split KPI meeting to their own meeting

---

peopleops/hiring.md

These tips were in Slab, but that didnt' end up hosting our handbook. So this change moves the content over so we capture it.

hiring: How to greenhouse
