flowforge/handbook

- company/team.md
When hired in a remote team it's not always clear what to expect on your
first day. For many folks coming from an office job this can be
daughting. Hope this helps them what to expect, and for the FlowForge
team to structure the onboarding.
> team: Onboarding information

- README.md
- development/index.md
Minor items missed on a5c7a85ece671d74e11302e0d3594e0e04f64625.
> fix: Broken link and MD linebreak

- peopleops/index.md
Cherry-picked changes from: https://github.com/flowforge/handbook/pull/15
> How to expense

- development/index.md
- development/packaging.md
- development/release.md
Outline the basic tasks needed for a release.
> First pass at relase docs

- company/team.md
As we might soon open a position for a new software developer I'm
documenting the process from now on onwards. This also allows candidates
to read what to expect.
> team: Describe interview process for new hires

- development/index.md
Added some words to cover our release planning process.
> Add words on planning releases

- peopleops/compensation.md
- peopleops/index.md
Recently a discussion was started around inflation compensation, which
kicked of broader questions this change tries to answer.
> peopleops: Document compensation and increases

- README.md
- company/index.md
- company/security.md
> Add start of security.md

- company/communication.md
Add guidelines for raising FlowForge in the Node-RED community
> Guidelines for raising FlowForge in NR community

- peopleops/index.md
Add details on:
- Brex cards for expenses
- Recording fixed assets over $500
- General policy on essential office equipment
> Add details on expenses policy

- company/communication.md
First iteration of async meetings is to implement Geekbot, to maintain
an up-to-date handbook, this iteration is now documented. From here we
can start iterating towards a better solution if needed.
> communication: Async standup meetings

- development/index.md
add allocating release manager 
Create next release  issue and assign
> Add actions to retro

- development/index.md
As our process evolves I capture some of it. Enabling others to alter or
extend the process.
> development: What to work on documenting

- README.md
- operations/billing.md
- operations/index.md
- operations/support.md
Some initial documenting of how we manage support and billing, this will evolve as we have real customers running through the process but this is what we have today.
> Ops - Support & Billing

- development/packaging.md
> fix broken link that connects to "Release Process"

- development/index.md
- development/staging.md
Some of the details on the staging environment, mostly just covers how it differs from prod.
> details of staging

- company/index.md
Minimal viable changes are important to get fast feedback cycles, and is
now part of our values under bias for action.
Transparency is a community-first trait, to allow information symmetry.
> values: Add MVP and transparency

- company/strategy.md
Explicitly state our two main objectives as a company. While these are
subject to change, like almost everything at our company, it's a long
horizon goal to create a competitive and attractive offering.
> strategy: Rewording of the page

- company/index.md
> Remove links no longer required

- company/strategy.md
The page contained date specific aims, which are in the past. As such
I've slightly reworded to future proof and remove outdated information.
> strategy: Remove outdated information

- development/release.md
> Include pre-reqs for release mgr

- operations/change.md
Ensure it's easy to use the same issue format to ease creation and handling of change request issues.
> change requests: Mention the issue template

- development/index.md
- development/release.md
Tried to do the releases today and wanted to make it easier for the next
developer to do this. Rough first iteration, but better than what we had
before.
> releases: Document how to do patch releases

- README.md
- company/strategy.md
- product/index.md
- product/plan.md
- product/pricing.md
- product/versioning.md
details of what we've discussed over our previous product calls.
Still TODO is to add the Business Rules around billing but that will follow in a separate PR
> Product planning

- development/index.md
As discussed in https://github.com/flowforge/admin/issues/68
> Add words on milestones/iterations on dev boards

- development/index.md
- development/security.md
Outline of a bug bounty policy.
> Add security policy

- development/release.md
This is to version the helm chart for each release
> Add yq to release pre-reqs

- operations/index.md
- operations/vendors.md
This change records how to enter our internal process to link for
external parties.
> bizz ops: How to file an invoice as vendor

- development/release.md
Update release process description.
See also https://github.com/flowforge/admin/pull/79 that updates the release process issue template.
> Update release process description

- development/release.md
Added some notes on release process for the unmanaged repositories
> Unmanaged releases

- peopleops/compensation.md
To ensure the process is clear to everyone it's now documented in the
handbook. This also gives a base line to improve on next year.
> peopleops: Explain the September performance review

- company/communication.md
Key metrics were reported monthly to both internal and external
stakeholeder. The metrics are and will remain to be the same, but with
internal stakeholders the plan is to briefly go over them each week.
> communication: Discuss key metrics in our weekly meeting

- development/packaging.md
We were missing details of the release-publish.yml automation
> Add details of release publish automation

- product/index.md
- product/verticals.md
> Market Verticals

- development/release.md
Following release 0.9.0, this PR aims to clarify some steps of the process as experienced for the first time.
(includes a couple of typo corrections)
> update wording and add URL links for quicker navigation

- peopleops/index.md
This requirement was already in place, just not documented.
> peopleops: Require memos for Brex

- company/communication.md
This PR contains 2 commits. One around Slack and that decisions, progress reports, etc aren't a great way to persist knowledge. The second around the 1:1 meeting.
Neither had a great deal documented so far, and as they're both communication related it felt time to record them in this PR.
> communication: Slack and 1:1 meeting pointers

- peopleops/index.md
As discussed in 1:1. I have opportunity to get a £139/month adhoc desk space at a local co-working space. Price wasn't considered an issue, so increasing the budget in handbook to reflect this.
> Increase budget to $150 & remove check with manager

- company/communication.md
- company/index.md
- company/remote.md
- company/security.md
- company/strategy.md
- development/contributing.md
- development/packaging.md
- operations/accounts.md
- operations/support.md
- peopleops/compensation.md
- peopleops/index.md
Fixed up things I noticed reading through the handbook.
While this is only a one-time fix, @ZJvandeWeg has proposed https://github.com/flowforge/handbook/pull/75 to add a GitHub action to handle this automatically.
> Typo and spelling fixes

- product/index.md
To quickly iterate on development and prioritization it's good to get a synchronous meeting to demo the current state and discuss improvements. This is the intent of internal product demo's.
> product: Internal product demo's

- product/index.md
Our customer calls haven't been structured, and not all yielded valuable feedback. Further, it's hard to scale learnings from customer calls throughout the organisation right now as the structure is different each time.
This change proposes a structure as first iteration, which should allow multiple people to have customer calls while the learnings can be done async by the whole organisation.
> product: Unified approach toward customer calls

- peopleops/hiring.md
While we haven't run into issues here, it's good to record that all offers extended should be considered conditional.
Either condition have a very low probability of being triggered, but better be up front about it.
> peopleops: Offers are conditional

- design/index.md
First pass at objectively defining our comms channels and content in the handbook.
> Add marketing processes to the Handbook.md

- company/communication.md
To create more coffee calls between team members I've deployed donut.com to our Slack to match 2 team members every two weeks to talk about anything, hopefully much more beyond work.
> coffee calls: Use Donut to schedule calls

- development/release.md
Document the use of `maintenance` branch for patch releases and the `backport` automation
> Update patch release process

- development/staging.md
Instructions for running devices with Staging.
> Add instructions for setting up GH npm token

- peopleops/hiring.md
An internal document has been created to collect STAR questions. We cannot record these in the handbook as candidates might prepare answers too well.
> peopleops: Start template for STAR interview questions

- company/communication.md
When an agenda is empty there's an opportunity to take a step back and validate what's working or not. This list is a small example on how to start such conversations.
> communication: Provide list of questions for the agenda

- README.md
- sales/index.md
As the company grows it's getting more challenging to maintain one pitch to prospects and customers. By documenting it's easier to track the sales pitch and update copy around the organisation to match.
> sales: Start page with Pitch

- peopleops/compensation.md
Got a question around stock compensation, and figured the Carta blog post would help others too.
> comp: Link to carta's explainer

- development/release.md
> Add flowforge-nr-persistent-context to repo list

- company/communication.md
ISO 8601 is a date format recently requested for another PR to the handbook, and I figured if it's a the standard we request in reviews it should be the default all-around.
- [-] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
- [-] Suitable unit/system level tests have been added and they pass
> comms: Request ISO 8601 for dates

- company/index.md
- company/strategy.md
- operations/data.md
- operations/index.md
While not a whole deal of significant information, I wanted to document early and often to keep this up to date.
> ops: Add the initial data stack to the handbook

- company/remote.md
- sales/index.md
[#193](https://github.com/flowforge/website/issues/193)
Had some uncommitted changes, only single liners, will push straight through.
> Uncommitted local changes

- operations/support.md
> Replace details of FreshDesk support with HubSpot

- sales/index.md
- sales/pitch.md
- sales/pricing.md
Split out the sections of the Sales Handbook section so that relevant categories appear in the side navigation for easier finding.
https://user-images.githubusercontent.com/99246719/211420767-6327c094-4de8-41f2-bd02-fc8e74518973.mov
https://github.com/flowforge/handbook/issues/180 - Part of the Handbook cleaning
> Reorganise Sales

- development/git-how-to.md
This section was authored whilst we did the re-org of the handbook, and was living in "Design" which felt a little out of place. Have moved it into "Development" and utilised the newly available `navTitle` property at the top of the `md` file so that it has a nice label in the side menu.
> Move "Using Git" & add nicer navTitle

- company/strategy.md
Focus on both breath and depth of adoption.
> kpi: Update to managed instances

- README.md
- design/design-thinking.md
- development/how-we-work/contributing.md
- development/how-we-work/packaging.md
- development/index.md
- marketing/videos.md
- product/verticals.md
With the newly added link testing on the website, we had 28 broken links in the handbook. This fixes all of them.
> Fix all broken Handbook links

- company/security.md
- operations/vendors.md
> fraud: Document money is never requested through email

- marketing/index.md
- marketing/webinars.md
> Adding webinars to handbook

- marketing/index.md
> Fix broken link error on marketing page

- development/how-we-work/staging.md
adds docs and links to the available email addresses to use when testing on staging.
> Add notes on staging emails

- company/communication.md
- company/remote.md
- company/security.md
- design/process.md
- design/tools.md
- development/how-we-work/contributing.md
- development/how-we-work/packaging.md
- development/how-we-work/staging.md
- development/releases/planning.md
- marketing/channels.md
- marketing/videos.md
- operations/accounts.md
- operations/data.md
- peopleops/compensation.md
- peopleops/expenses.md
- peopleops/organization.md
- product/plan.md
- product/pricing.md
- product/verticals.md
Part of https://github.com/flowforge/flowforge/issues/554, tool assisted full spell check and fix of spelling errors and typos in the handbook.
https://github.com/flowforge/flowforge/issues/554
> Typo and spell fixes

- development/markdown-how-to.md
Working with tracy, thought it would be beneficial to have a quick how-to guide on the most common Markdown formats
> Add short markdown "how-to"

- development/markdown-how-to.md
Demonstrates how newlines are handled in markdown, and blank lines used to separate paragraphs.
> Expand markdown paragraph example

- company/communication.md
- company/index.md
- company/principles.md
- company/security.md
- peopleops/compensation.md
- peopleops/expenses.md
- peopleops/leave.md
- peopleops/performance-review.md
As there were forward looking statements in the handbook on what the company will do, but might not be in a position to offer. With these changes I hope to reduce those instances for the future.
> Rewording of company and peopleops sections

- development/git-how-to.md
For https://github.com/flowforge/website/issues/472
> Skip image parsing of the giant gif files

- development/git-how-to.md
> Also skip new file

- marketing/boilerplate.md
- marketing/index.md
Add to Handbook boiler plate description of FlowForge.
> New FlowForge boiler plate descriptions

- peopleops/compensation.md
We do offer health care to employees in CA, and IN too. Now this is documented.
> Add health care as benefit

- marketing/boilerplate.md
Update boiler plate section to include company tagline and one sentence description.
> Update boiler plate with tagline and one sentence description
